# This file was generated by GoReleaser. DO NOT EDIT.
cask "pipectl" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_darwin_amd64.tar.gz"
      sha256 "e6da457f669d4918c6d4a10fb833d5f03e43d1676f52ab9320b8520092c43e75"
    end
    on_arm do
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_darwin_arm64.tar.gz"
      sha256 "cfec0263d4e4debe351c90835e24f32c6439b69112888eb54f562976c8acc0e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_linux_amd64.tar.gz"
      sha256 "0955296048f2883f3d0e13a14362f78a00b3820aff58d09592389abfaf0f7b8e"
    end
    on_arm do
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_linux_arm64.tar.gz"
      sha256 "f809729391295903244607c72764624cf61e3912181fd9bd2526c4d1d3d6a24f"
    end
  end

  name "pipectl"
  desc "Run YAML-defined data pipelines from the command line."
  homepage "https://github.com/pipectl/pipectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pipectl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pipectl"]
  end

  # No zap stanza required

end
