# This file was generated by GoReleaser. DO NOT EDIT.
cask "pipectl" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "ac691a81f4970ff2b5c86e70e44c19c1d31ac915fd6eed4eb832ff41543a0ef5"
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "76b524df71e9333fd4ef013e54141d31a863611594dcac43f98ee418eb683f48"
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af53bd06e4ce1dd4eefa9faf37f1d6b9d1445412766ba668df92032b1029a041"
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "db165afe9263f448f79b061979655fa5e735b057ee4304900c45d75898c04b75"
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pipectl"
  desc "Run YAML-defined data pipelines from the command line."
  homepage "https://github.com/pipectl/pipectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pipectl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pipectl"]
  end

  # No zap stanza required

end
