# This file was generated by GoReleaser. DO NOT EDIT.
cask "pipectl" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_darwin_amd64.tar.gz"
      sha256 "5649fb409a9516c30c2e61c4147be131ac51c036f3f1d683380fdfb9faf20518"
    end
    on_arm do
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_darwin_arm64.tar.gz"
      sha256 "70796be5052139b0a9f373733b2a88e1c8b6a35209a322502a239ba529634a3b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_linux_amd64.tar.gz"
      sha256 "0eef1d3ad32a02bc7afa80ac861e35ef2ea12c4f254b1dc4a90a628d81372a2d"
    end
    on_arm do
      url "https://github.com/pipectl/pipectl/releases/download/v#{version}/pipectl_#{version}_linux_arm64.tar.gz"
      sha256 "a3649b7427616dcdcacfaf5441652f58134eef8f2fa389ef2deebec301c7ee0e"
    end
  end

  name "pipectl"
  desc "Run YAML-defined data pipelines from the command line."
  homepage "https://github.com/pipectl/pipectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pipectl"

  postflight do
    system_command '/usr/bin/xattr', args: ['-dr', 'com.apple.quarantine', '#{staged_path}/pipectl']
  end

  # No zap stanza required

end
